### PR TITLE
Fix the examples in section 2.1.1

### PR DESCRIPTION
**Pull request by msramek**
Missing brackets in the 'cookies' and 'storage' examples and consistency
of the 'executionContexts' example.

Also, refresh the html file.

### CODE REVIEW

**Comment by mikewest** [comment]
Thanks!

**Comment by mikewest** [comment]
@wseltzer: Can you add @msramek to the list of folks approved for commits (or delegate the addition to one of your minions? :) )? He works with me at Google, and should be covered by our general IPR commitment.

**Comment by msramek** [comment]
@wseltzer: Friendly ping on the above request! I'm still contributing to this repository, and am still seeing red ipr checks on my pull requests.

Thanks!

**Comment by wseltzer** [comment]
@msramek can you join WebAppSec?

**Comment by msramek** [comment]
Hello again @wseltzer! Sorry for the long delay in my response.

As you may have seen, I did join WebAppSec as a participant for Google. In the meantime, I do still get "contribution issues" warnings on my pull requests, I assume additional action is required? Thanks!

**Comment by wseltzer** [comment]
Thanks @msramek. I linked the IDs so you should be all set now.

**Pull request merged**
